server:
  port: 8081
  servlet:
    context-path: /crm-service
#  tomcat:
#    max-http-form-post-size: 20MB # 设置内置Tomcat请求大小为20MB

logging:
  level:
    com.ytl.crm.mapper: debug

spring:
  datasource:
    druid:
      url: jdbc:mysql://rm-2ze2hx8k7js6pk5y5.mysql.rds.aliyuncs.com:3306/crm_service?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
      username: root123
      password: root123@@
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false


#mybatis的相关配置
mybatis:
  mapper-locations: classpath*:/mybatis/**/*.xml

#swagger:
#  enable:
#    switch: true


jwt:
  secret: toker
  expiration: 604800000

